### ISSUE TITLE
工具报错，只运行一条就停止了。

### ISSUE THREAD

**Issue by Curta7n** [smxiazi/xp_CAPTCHA#6]
`	at org.python.proxies.__main__$xp_CAPTCHA_api$8.getNextPayload(Unknown Source)
	at burp.ax_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Traceback (most recent call last):
  File "/Users/Tools/misc/xp_CAPTCHA/xp_CAPTCHA.py", line 73, in getNextPayload
    if re.findall('"\s*:\s*.?"', CAPTCHA):
  File "/Users/Tools/burp/jython-standalone-2.7.2.jar/Lib/re.py", line 177, in findall
TypeError: expected string or buffer, but got <type 'instance'>`

**Comment by smxiazi** [comment]
稍等一下。我看看

**Comment by smxiazi** [comment]
已修复，你在试试
