### ISSUE TITLE
加载插件时乱码

### ISSUE THREAD

**Issue by Grouppppp** [smxiazi/xp_CAPTCHA#7]
xp_CAPTCHA  ä¸­æå:çè·éªè¯ç 
blogï¼http://www.nmd5.com/
T00lsï¼https://www.t00ls.net/ 
The lonerå®å¨å¢é author:ç®å½ç¸å­

ç¨æ³ï¼
å¨headå¤´é¨æ·»å xiapao:éªè¯ç çURL

å¦ï¼

POST /login HTTP/1.1

我试了很多方法，字符串前加u的话，会直接报错 UnicodeEncodeError: 'ascii' codec can't encode characters in position
请问有什么解决方案吗？

**Comment by smxiazi** [comment]
这个不太重要，插件功能能用即可。

**Comment by Grouppppp** [comment]
测了好多次，功能并不正常。原因是登录前没有 cookie 字段，所以会报错，导致Intruder直接变成完成。

**Comment by Grouppppp** [comment]
Traceback (most recent call last):
  File "D:\Tools\Burp Suite Professional\xp_CAPTCHA.py", line 29, in createNewInstance
    return xp_CAPTCHA(attack)
  File "D:\Tools\Burp Suite Professional\xp_CAPTCHA.py", line 34, in __init__
    cookie = re.findall("Cookie: (.+?)\r\n", tem)[0] #��?��???cookie
IndexError: index out of range: 0

	at org.python.core.Py.IndexError(Py.java:251)
	at org.python.core.SequenceIndexDelegate.checkIdxAndGetItem(SequenceIndexDelegate.java:63)
	at org.python.core.PySequence.seq___getitem__(PySequence.java:378)
	at org.python.core.PySequence.__getitem__(PySequence.java:374)
	at org.python.pycode._pyx4.__init__$6(D:/Tools/Burp Suite Professional/xp_CAPTCHA.py:43)
	at org.python.pycode._pyx4.call_function(D:/Tools/Burp Suite Professional/xp_CAPTCHA.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:20)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:2408)
	at org.python.core.PyType.__call__(PyType.java:2389)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx4.createNewInstance$4(D:/Tools/Burp Suite Professional/xp_CAPTCHA.py:29)
	at org.python.pycode._pyx4.call_function(D:/Tools/Burp Suite Professional/xp_CAPTCHA.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3565)
	at org.python.core.PyObject._jcall(PyObject.java:3598)
	at org.python.proxies.__main__$BurpExtender$7.createNewInstance(Unknown Source)
	at burp.e06.a(Unknown Source)
	at burp.e06.lambda$getNewInstance$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by smxiazi** [comment]
如果没有cookie，可以自己在头部添加cookie字段，如：Cookie: test=1

**Comment by Grouppppp** [comment]
可否给一个结合 captcha-killer-modified 插件用的发包模版呢？

**Comment by Grouppppp** [comment]
确实，手动添加 Cookie 字段更简单一些。我刚才在代码里把 cookie 相关的代码注释掉了，测试也能用了。
